"""rebuild schema

Revision ID: 08bbea7fc671
Revises: 
Create Date: 2026-02-16 22:03:55.664386

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = '08bbea7fc671'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='소속 기관명'),
    sa.Column('type', sa.Enum('UNIVERSITY', 'GOVERNMENT', 'COMPANY', 'ETC', name='affiliation_type'), nullable=False, comment='소속 유형 (UNIVERSITY, GOVERNMENT, COMPANY, ETC)'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='이메일 도메인 (e.g., snu.ac.kr)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=True),
    sa.Column('industry_code', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_created_at', 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_corp_code'), 'companies', ['corp_code'], unique=True)
    op.create_index(op.f('ix_companies_stock_code'), 'companies', ['stock_code'], unique=True)
    op.create_table('job_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='직무 카테고리명 (e.g., 마케팅)'),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True, comment='핵심 역량 키워드 리스트'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 카테고리 ID (Self-referencing)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['job_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('role', sa.Enum('JOB_SEEKER', 'MANAGER', 'SYSTEM_ADMIN', name='user_role'), nullable=False, comment='사용자 역할'),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='user_tier'), nullable=False, comment='구독 등급'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reprt_code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('rcept_dt', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no')
    )
    op.create_table('company_talents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True, comment='기준 연도'),
    sa.Column('core_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='핵심 가치 리스트 (List[str])'),
    sa.Column('description', sa.Text(), nullable=True, comment='인재상 상세 설명'),
    sa.Column('source_url', sa.String(length=2048), nullable=True, comment='출처 URL'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_talents_company_id'), 'company_talents', ['company_id'], unique=False)
    op.create_table('job_seeker_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=True, comment='소속 ID (비소속 시 Null)'),
    sa.Column('student_id', sa.String(length=50), nullable=True, comment='학번 (해당 시)'),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='학력 정보 (학교, 전공, 상태)'),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='스펙 정보 (어학, 자격증, 경력)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('manager_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False, comment='소속 ID (관리자는 필수)'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='부서명'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('report_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('resume_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='지원 기업 ID (선택)'),
    sa.Column('job_category_id', sa.Integer(), nullable=True, comment='직무 카테고리 ID (선택)'),
    sa.Column('job_text', sa.String(length=255), nullable=True, comment='사용자 직접 입력 직무명 (보존용)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='자소서 세트 제목'),
    sa.Column('target_season', sa.String(length=20), nullable=True, comment='목표 채용 시즌 (e.g., 2026-1H)'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='아카이브 여부'),
    sa.Column('applicant_type', sa.Enum('NEW', 'EXPERIENCED', name='applicant_type'), server_default='NEW', nullable=False, comment='지원자 유형 (신입/경력)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_questions_company_id'), 'resume_questions', ['company_id'], unique=False)
    op.create_index(op.f('ix_resume_questions_user_id'), 'resume_questions', ['user_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('toc_text', sa.Text(), nullable=True),
    sa.Column('references_data', sa.JSON(), nullable=True),
    sa.Column('conversation_log', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['report_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('MOTIVATION', 'COMPETENCY', 'CHALLENGE', 'COLLABORATION', 'VALUES', 'SOCIAL_ISSUE', name='resume_item_type'), nullable=False, comment='문항 유형 (지원동기, 직무역량 등)'),
    sa.Column('content', sa.Text(), nullable=False, comment='문항 지문'),
    sa.Column('max_length', sa.Integer(), nullable=True, comment='최대 글자수 제한'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='문항 순서'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['resume_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_items_question_id'), 'resume_items', ['question_id'], unique=False)
    op.create_table('source_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_report_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('table_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', VECTOR(dim=768), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='사용자 작성 본문'),
    sa.Column('version', sa.Integer(), nullable=False, comment='버전 번호 (문항 내 자동 증가)'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='현재 활성 버전 여부'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['resume_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_drafts_item_id'), 'resume_drafts', ['item_id'], unique=False)
    op.create_table('resume_feedbacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False, comment='사용된 AI 모델명'),
    sa.Column('guide_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='작성 가이드 데이터'),
    sa.Column('correction_content', sa.Text(), nullable=True, comment='첨삭 완성본 (코칭 결과)'),
    sa.Column('feedback_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='3-Point 피드백 (강점, 보완점, 제안)'),
    sa.Column('score', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='항목별 점수'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['resume_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_feedbacks_draft_id'), 'resume_feedbacks', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_feedbacks_draft_id'), table_name='resume_feedbacks')
    op.drop_table('resume_feedbacks')
    op.drop_index(op.f('ix_resume_drafts_item_id'), table_name='resume_drafts')
    op.drop_table('resume_drafts')
    op.drop_table('source_materials')
    op.drop_index(op.f('ix_resume_items_question_id'), table_name='resume_items')
    op.drop_table('resume_items')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_resume_questions_user_id'), table_name='resume_questions')
    op.drop_index(op.f('ix_resume_questions_company_id'), table_name='resume_questions')
    op.drop_table('resume_questions')
    op.drop_table('report_jobs')
    op.drop_table('manager_profiles')
    op.drop_table('job_seeker_profiles')
    op.drop_index(op.f('ix_company_talents_company_id'), table_name='company_talents')
    op.drop_table('company_talents')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('job_categories')
    op.drop_index(op.f('ix_companies_stock_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_corp_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index('idx_company_created_at', table_name='companies')
    op.drop_table('companies')
    op.drop_table('affiliations')
    # ### end Alembic commands ###
