"""make_report_job_company_id_nullable

Revision ID: 4d43e67a940c
Revises: b13b2bd275b9
Create Date: 2026-02-20 14:06:19.643847

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = '4d43e67a940c'
down_revision = 'b13b2bd275b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_jobs', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_jobs', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
