"""add external_informations table

Revision ID: 9247b74d363e
Revises: 4d43e67a940c
Create Date: 2026-02-25 15:33:32.560977

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = '9247b74d363e'
down_revision = '4d43e67a940c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_informations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False, comment='검색 결과 원본 URL'),
    sa.Column('url_hash', sa.String(length=64), nullable=False, comment='URL의 SHA-256 해시 (중복 방지용 고유 키)'),
    sa.Column('title', sa.String(length=1000), nullable=False, comment='페이지 제목'),
    sa.Column('snippets', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='검색 스니펫 목록 (JSON 배열)'),
    sa.Column('description', sa.Text(), nullable=True, comment='페이지 설명'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='출처 유형 (WEB, DART, INTERNAL)'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='관련 기업명'),
    sa.Column('job_id', sa.String(length=36), nullable=True, comment='수집 시점의 Job UUID'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='데이터 수집 시점'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash'),
    sa.UniqueConstraint('url_hash', name='uq_external_informations_url_hash')
    )
    op.create_index(op.f('ix_external_informations_company_name'), 'external_informations', ['company_name'], unique=False)
    op.create_index(op.f('ix_external_informations_job_id'), 'external_informations', ['job_id'], unique=False)
    op.create_index(op.f('ix_external_informations_url'), 'external_informations', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_informations_url'), table_name='external_informations')
    op.drop_index(op.f('ix_external_informations_job_id'), table_name='external_informations')
    op.drop_index(op.f('ix_external_informations_company_name'), table_name='external_informations')
    op.drop_table('external_informations')
    # ### end Alembic commands ###
