"""Add company analysis request fields to report_jobs

Revision ID: b13b2bd275b9
Revises: 08bbea7fc671
Create Date: 2026-02-19 16:02:44.862257

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy.vector import VECTOR


# revision identifiers, used by Alembic.
revision = 'b13b2bd275b9'
down_revision = '08bbea7fc671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_jobs', sa.Column('user_id', sa.BigInteger(), nullable=False, comment='분석을 요청한 구직자의 user_id'))
    op.add_column('report_jobs', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True, comment='요청 시간 (TimestampMixin의 created_at과 별개로 추적)'))
    op.add_column('report_jobs', sa.Column('approved_by', sa.BigInteger(), nullable=True, comment='승인한 관리자의 user_id'))
    op.add_column('report_jobs', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='승인 시간'))
    op.add_column('report_jobs', sa.Column('rejection_reason', sa.Text(), nullable=True, comment='반려 사유 (REJECTED 상태일 때만 입력)'))
    op.add_column('report_jobs', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True, comment='반려 시간'))
    op.create_foreign_key(None, 'report_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report_jobs', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_jobs', type_='foreignkey')
    op.drop_constraint(None, 'report_jobs', type_='foreignkey')
    op.drop_column('report_jobs', 'rejected_at')
    op.drop_column('report_jobs', 'rejection_reason')
    op.drop_column('report_jobs', 'approved_at')
    op.drop_column('report_jobs', 'approved_by')
    op.drop_column('report_jobs', 'requested_at')
    op.drop_column('report_jobs', 'user_id')
    # ### end Alembic commands ###
